version: '3.8' 

services:
  # 1. Backend servisi (Django)
  backend:
    build: . 
    container_name: homesecurity_backend
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/app  
    ports:
      - "8000:8000" 
    env_file:
      - .env 
    depends_on:
      - db 
      - redis

  # 2. Redis (WebSocket ve Kanal katmanı için)
  redis:
    image: redis:7-alpine
    container_name: homesecurity_redis
    ports:
      - "6379:6379"
    restart: always

  # 3. Veritabanı (PostgreSQL 16) 
  db:
    image: postgres:16-alpine
    container_name: homesecurity_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  # 4. Keycloak (Kimlik Yönetimi)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1 # Sürümü 23.0.1 olarak sabitledik
    container_name: homesecurity_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      #Bilgisayarındaki realm-export.json dosyasını konteynere bağladık
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: 
      - start-dev 
      - --import-realm # Başlangıçta dosyayı otomatik içe aktarır
    depends_on:
      - db

volumes:
  postgres_data: