"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials
import json
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env') # .env dosyası backend-api ana dizininde olduğu için bir üst klasöre bakıyoruz


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key') # .env dosyasından key okunur, yoksa default kullanılır 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    # django uygulamaları
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # üçüncü taraf uygulamalar (benim eklediklerim)
    'core',  # veritabanı modelleri için core eklendi
    'rest_framework',  # DRF için, API oluşturmak için
    'corsheaders',  # CORS için, mobil için erişim
    'drf_spectacular', #drf için ui eklenti
    'channels', #websocket için

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # CORS isteklerini yakalamak için en üste eklenmelidir
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Standart WSGI yerine Asenkron ASGI kullanacağımızı belirtiyoruz
ASGI_APPLICATION = 'config.asgi.application'

# Redis Bağlantı Ayarları (Docker-compose içindeki redis servisine işaret eder)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            #"hosts": [('redis', 6379)], # Eğer localde çalışıyorsan ve Redis ayrıysa ('127.0.0.1', 6379) olabilir.
            "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # Railway ortamı: DATABASE_URL tek env var ile tüm bağlantıyı sağlar
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL)}
else:
    # Local/Docker ortamı: ayrı env var'lardan okunur
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': os.getenv('POSTGRES_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', #drf için dokümentasyon ui eklenti
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.KeycloakJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

#dokümentasyondaki başlıklar   
SPECTACULAR_SETTINGS = {
    'TITLE': 'Home Security API',
    'DESCRIPTION': 'Capstone project Backend API description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, 
}

# Keycloak JWT Doğrulama Ayarları
KEYCLOAK_SERVER_URL = os.getenv('KEYCLOAK_SERVER_URL', 'http://localhost:8080')
KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM', 'SmartHomeRealm')

SIMPLE_JWT = {
    'ALGORITHM': 'RS256',
    'JWK_URL': f"{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs",
    'ISSUER': f"{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}",
    'USER_ID_CLAIM': 'preferred_username',
    'USER_ID_FIELD': 'username',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.UntypedToken',),
    'AUDIENCE': None,
}
# Geliştirme aşamasında mobil ve web'den gelen tüm isteklere izin vermek için:
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# --- FIREBASE ADMIN SDK INITIALIZATION ---
firebase_creds_json = os.getenv('FIREBASE_JSON_CREDENTIALS')

if not firebase_admin._apps:
    if firebase_creds_json:
        # Metin olarak gelen JSON'u sözlüğe çevir
        cred_dict = json.loads(firebase_creds_json)
        cred = credentials.Certificate(cred_dict)
        firebase_admin.initialize_app(cred)
    else:
        print("Uyarı: FIREBASE_JSON_CREDENTIALS ortam değişkeni bulunamadı!")

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
