# Generated by Django 5.0.1 on 2026-01-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='is_authorized',
        ),
    ]
