# Generated by Django 5.0.1 on 2026-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_sub_type',
            field=models.CharField(choices=[('SMOKE', 'Duman Sensörü (MQ-2)'), ('GAS', 'Gaz Sensörü (MQ-6)'), ('WATER', 'Su Baskını Sensörü'), ('MOTION', 'Hareket Sensörü (PIR)'), ('VIBRATION', 'Titreşim/Deprem Sensörü'), ('PUMP', 'Tahliye Pompası'), ('BUZZER', 'Sesli Alarm'), ('NFC', 'NFC Giriş Modülü')], default='SMOKE', max_length=20),
        ),
    ]
