# Generated by Django 5.0.1 on 2026-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_device_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='alarm_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='is_armed',
            field=models.BooleanField(default=False),
        ),
    ]
