# Generated by Django 5.0.1 on 2026-05-14 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_home_alarm_triggered_home_is_armed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_sub_type',
            field=models.CharField(choices=[('SMOKE', 'Duman Sensörü (MQ-2)'), ('GAS', 'Gaz Sensörü (MQ-6)'), ('WATER', 'Su Baskını Sensörü'), ('MOTION', 'Hareket Sensörü (PIR)'), ('VIBRATION', 'Titreşim/Deprem Sensörü'), ('PUMP', 'Tahliye Pompası'), ('BUZZER', 'Sesli Alarm'), ('NFC', 'NFC Giriş Modülü'), ('MAGNETIC', 'Manyetik Kapı/Pencere Sensörü'), ('FLOW', 'Su Akış Sensörü (YF-S201)')], default='SMOKE', max_length=20),
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='core.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
