# Generated by Django 5.0.1 on 2026-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_device_device_sub_type_nfctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
